version: '3.4'

services:
  iottasks:
    image: hunter99/iottasks:v1
    #build:
     # context: .
      #dockerfile: IOTTasks/Dockerfile
    ports: 
      - "8000:80"
    #volumes:
      #- .:/src
    depends_on:
       - mongodb


  mongodb: 
    image: mongo
    container_name: my_mongo_db
    restart: always
    volumes: 
      #- ${WEBAPP_STORAGE_HOME}/site:/data/db
      - './bin/data:/data/db'
    ports:
      - "27017:27017"
