version: '3.4'

services:
  mongodb: 
    image: mongo
    container_name: my_mongo_db
    restart: always
    volumes: 
      - './bin/data:/data/db'
    ports:
      - "27017:27017"

  web_app:
    image: hunter99/iottasks:v1
    ports: 
      - "8000:80"
    volumes:
      - "./:/src"
    depends_on:
       - mongodb
    links:
       - mongodb

