version: '3.4'

services:
  mongo: 
    image: mongo
    container_name: mongo
    restart: always
    volumes: 
     - './bin/data:/data/db'
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - "8088:8081"
    depends_on:
      - mongo
    links:
      - mongo

  iottasks:
    #image: hunter99/iottasks:v3
    image: ${DOCKER_REGISTRY-}iottasks
    build:
      context: .
      dockerfile: IOTTasks/Dockerfile
    ports: 
      - "8081:80"
    volumes:
      - ".:/src"
    depends_on:
       - mongo
    links:
       - mongo

